server:
  servlet:
    context-path: /point-grabber
  port: 8888

logging:
  level:
    root: info

account:
  baidu:
    username: ''
    password: ''

webdriver:
  chrome:
    path: '/Users/peakrock/my/src/coding-thinking/point-grabber/drivers/chrome-79.0.3945.36/chromedriver'